language: python

python:
  - "3.6"

env:
  global: SCIDB_VER=19.11 ARROW_VER=0.9.0-1
  jobs:
    - SCIDB_IMG=          TEST_BASIC=true
    - SCIDB_IMG=-xenial   TEST_BASIC=true
    - SCIDB_IMG=-xenial   TEST_BASIC=false
    - SCIDB_IMG=-centos-7 TEST_BASIC=true
    - SCIDB_IMG=-centos-7 TEST_BASIC=false

services:
  - docker

before_install:
  - if [ "$TEST_BASIC" = "false" ]; then
      wget --no-verbose --output-document -
        https://github.com/Paradigm4/accelerated_io_tools/archive/v${SCIDB_VER}.2.tar.gz
        | tar --extract --gzip --directory=. ;
      wget --no-verbose --output-document -
        https://github.com/Paradigm4/superfunpack/archive/v${SCIDB_VER}.1.tar.gz
        | tar --extract --gzip --directory=. ;
    fi

  - docker pull rvernica/scidb:${SCIDB_VER}${SCIDB_IMG}

  - docker run
    --detach
    --env ARROW_VER=$ARROW_VER
    --name scidb
    --publish 8080:8080
    --tmpfs /dev/shm
    --volume /dev/shm
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume /tmp/$(mktemp --directory):/run
    --volume `pwd`:/shim
    rvernica/scidb:${SCIDB_VER}${SCIDB_IMG}

  - if [ "$SCIDB_IMG" = "-centos-7" ]; then
      docker exec scidb /opt/scidb/$SCIDB_VER/bin/scidbctl.py start scidb ;
      docker exec scidb systemctl start shimsvc ;
    fi

  - while ! curl http://localhost:8080/version; do sleep 1; done

  - if [ "$SCIDB_IMG" = "-centos-7" ]; then
      docker exec scidb systemctl stop shimsvc ;
    else
      docker exec scidb service shimsvc stop ;
    fi

install:
  - docker exec scidb /shim/tests/docker-install.sh $TEST_BASIC
  - docker exec scidb make --directory=/shim install
  - pip install --upgrade -r tests/pytest/requirements.txt

script:
  - if [ "$TEST_BASIC" = "true" ]; then
      docker exec scidb make --directory=/shim test_basic ;
    else
      docker exec scidb make --directory=/shim test ;
      docker exec scidb env AIO=aio make --directory=/shim test ;
    fi

  - docker exec scidb /shim/shim start
  - pytest tests/pytest/test_sessions.py
  - pytest -n 2 tests/pytest/test_sessions_multi.py

after_failure:
  - docker logs scidb
